fix conflicts

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,3 +1,5 @@
+# yamllint disable rule:line-length rule:truthy
+name: Release
 # Generated by: gromit policy
 
 # Distribution channels covered by this workflow
@@ -305,6 +307,50 @@ jobs:
         id: fetch_slack_user
         uses: TykTechnologies/github-actions/.github/actions/github-to-slack@main
         with:
+          report_xml: 'true'
+          execution_status: ${{ steps.test_execution.outcome }}
+  aggregator-ci-test:
+    name: Aggregated CI Status
+    runs-on: ubuntu-latest
+    # Dynamically determine which jobs to depend on based on repository configuration
+    needs: [goreleaser, api-tests]
+    if: ${{ always() && github.event_name == 'pull_request' }}
+    steps:
+      - name: Aggregate results
+        run: |
+          failed=()
+          # Get the needs context as JSON once
+          needs_json='${{ toJSON(needs) }}'
+
+          # Loop through all jobs in the needs context
+          for job in $(echo "$needs_json" | jq -r 'keys[]'); do
+            job_result=$(echo "$needs_json" | jq -r --arg job "$job" '.[$job].result')
+
+            if [[ "$job_result" != "success" ]]; then
+              failed+=("$job")
+            fi
+          done
+
+          if (( ${#failed[@]} )); then
+            # Join the failed job names with commas
+            failed_jobs=$(IFS=", "; echo "${failed[*]}")
+            echo "❌ Failed jobs ----- : $failed_jobs"
+            exit 1
+          fi
+
+          echo "✅ All required jobs succeeded"
+  test-controller-distros:
+    if: github.event.pull_request.draft == false
+    needs:
+      - goreleaser
+    runs-on: ubuntu-latest
+    outputs:
+      deb: ${{ steps.params.outputs.deb }}
+      rpm: ${{ steps.params.outputs.rpm }}
+    steps:
+      - name: set params
+        id: params
+        shell: bash
           github_email: ${{ env.GIT_USER_EMAIL }}
       - name: Notify slack
         if: ${{ steps.test_execution.outcome != 'success' && !github.event.pull_request.draft }}
