TT-15780: add aggregator job to release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,5 +1,30 @@
 # yamllint disable rule:line-length rule:truthy
 name: Release
+# DEBUG INFORMATION
+# ================
+# Repository Name: tyk-pump
+# Branch: master
+# Features: distroless, releng
+# Tests: api
+
+# Buildenv: 1.24-bookworm
+# BaseImage: debian:trixie-slim
+# DistrolessBaseImage: static-debian12:nonroot
+# Cgo: false
+# ConfigFile: pump.conf
+# VersionPackage: github.com/TykTechnologies/tyk-pump/pumps
+# UpgradeFromVer: 1.6.0
+
+# Owner: TykTechnologies
+# PackageName: tyk-pump
+# Binary: tyk-pump
+# Default: 
+
+# Builds Keys:
+# 
+#   - std
+# 
+
 # Generated by: gromit policy
 
 # Distribution channels covered by this workflow
@@ -49,7 +74,6 @@ jobs:
             rpmvers: 'el/7 el/8 el/9 amazon/2 amazon/2023'
             debvers: 'ubuntu/xenial ubuntu/bionic ubuntu/focal ubuntu/jammy ubuntu/noble debian/jessie debian/buster debian/bullseye debian/bookworm debian/trixie'
     outputs:
-      fips_tags: ${{ steps.ci_metadata_fips.outputs.tags }}
       std_tags: ${{ steps.ci_metadata_std.outputs.tags }}
       commit_author: ${{ steps.set_outputs.outputs.commit_author}}
     steps:
@@ -131,71 +155,6 @@ jobs:
         if: ${{ matrix.golang_cross == '1.24-bookworm' }}
         with:
           mask-password: 'true'
-      - name: Docker metadata for fips CI
-        id: ci_metadata_fips
-        if: ${{ matrix.golang_cross == '1.24-bookworm' }}
-        uses: docker/metadata-action@v5
-        with:
-          images: |
-            ${{ steps.ecr.outputs.registry }}/tyk-pump-fips
-          flavor: |
-            latest=false
-          tags: |
-            type=ref,event=branch
-            type=ref,event=pr
-            type=sha,format=long
-            type=semver,pattern={{major}},prefix=v
-            type=semver,pattern={{major}}.{{minor}},prefix=v
-            type=semver,pattern={{version}},prefix=v
-      - name: push fips image to CI
-        if: ${{ matrix.golang_cross == '1.24-bookworm' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: "dist"
-          platforms: linux/amd64
-          file: ci/Dockerfile.distroless
-          provenance: mode=max
-          sbom: true
-          push: true
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          tags: ${{ steps.ci_metadata_fips.outputs.tags }}
-          labels: ${{ steps.ci_metadata_fips.outputs.labels }}
-          build-args: |
-            BUILD_PACKAGE_NAME=tyk-pump-fips
-      - name: Docker metadata for fips tag push
-        id: tag_metadata_fips
-        uses: docker/metadata-action@v5
-        with:
-          images: |
-            tykio/tyk-pump-fips
-          flavor: |
-            latest=false
-            prefix=v
-          tags: |
-            type=semver,pattern={{major}}.{{minor}}
-            type=semver,pattern={{version}}
-          labels: |
-            org.opencontainers.image.title=Tyk Analytics Pump FIPS
-            org.opencontainers.image.description=Tyk Analytics Pump to move analytics data from Redis to any supported back end (multiple back ends can be written to at once). This version is compiled with boringssl.
-            org.opencontainers.image.vendor=tyk.io
-            org.opencontainers.image.version=${{ github.ref_name }}
-      - name: push fips image to prod
-        if: ${{ matrix.golang_cross == '1.24-bookworm' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: "dist"
-          platforms: linux/amd64
-          file: ci/Dockerfile.distroless
-          provenance: mode=max
-          sbom: true
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          push: ${{ startsWith(github.ref, 'refs/tags') }}
-          tags: ${{ steps.tag_metadata_fips.outputs.tags }}
-          labels: ${{ steps.tag_metadata_fips.outputs.labels }}
-          build-args: |
-            BUILD_PACKAGE_NAME=tyk-pump-fips
       - name: Docker metadata for std CI
         id: ci_metadata_std
         if: ${{ matrix.golang_cross == '1.24-bookworm' }}
@@ -363,6 +322,36 @@ jobs:
         with:
           report_xml: 'true'
           execution_status: ${{ steps.test_execution.outcome }}
+  aggregator-ci-test:
+    name: Aggregated CI Status
+    runs-on: ubuntu-latest
+    # Dynamically determine which jobs to depend on based on repository configuration
+    needs: [goreleaser, api-tests]
+    if: ${{ always() && github.event_name == 'pull_request' }}
+    steps:
+      - name: Aggregate results
+        run: |
+          failed=()
+          # Get the needs context as JSON once
+          needs_json='${{ toJSON(needs) }}'
+
+          # Loop through all jobs in the needs context
+          for job in $(echo "$needs_json" | jq -r 'keys[]'); do
+            job_result=$(echo "$needs_json" | jq -r --arg job "$job" '.[$job].result')
+
+            if [[ "$job_result" != "success" ]]; then
+              failed+=("$job")
+            fi
+          done
+
+          if (( ${#failed[@]} )); then
+            # Join the failed job names with commas
+            failed_jobs=$(IFS=", "; echo "${failed[*]}")
+            echo "❌ Failed jobs ----- : $failed_jobs"
+            exit 1
+          fi
+
+          echo "✅ All required jobs succeeded"
   test-controller-distros:
     if: github.event.pull_request.draft == false
     needs:
